// Generated by scripts/generate-formats.ts. Do not edit.

import type { PaneId, SafeInteger, SessionId, WindowId } from "./common.js";

export type FormatScope =
  | "buffer"
  | "client"
  | "context"
  | "event"
  | "pane"
  | "session"
  | "universal"
  | "window";

export type FormatFieldName =
  | "active_window_index"
  | "alternate_on"
  | "alternate_saved_x"
  | "alternate_saved_y"
  | "bracket_paste_flag"
  | "buffer_name"
  | "buffer_sample"
  | "buffer_size"
  | "client_activity"
  | "client_cell_height"
  | "client_cell_width"
  | "client_control_mode"
  | "client_created"
  | "client_discarded"
  | "client_flags"
  | "client_height"
  | "client_key_table"
  | "client_last_session"
  | "client_mode_format"
  | "client_name"
  | "client_pid"
  | "client_prefix"
  | "client_readonly"
  | "client_session"
  | "client_termfeatures"
  | "client_termname"
  | "client_termtype"
  | "client_tty"
  | "client_uid"
  | "client_user"
  | "client_utf8"
  | "client_width"
  | "client_written"
  | "command_list_alias"
  | "command_list_name"
  | "command_list_usage"
  | "config_files"
  | "copy_cursor_line"
  | "copy_cursor_word"
  | "copy_cursor_x"
  | "copy_cursor_y"
  | "current_file"
  | "cursor_blinking"
  | "cursor_character"
  | "cursor_colour"
  | "cursor_flag"
  | "cursor_shape"
  | "cursor_very_visible"
  | "cursor_x"
  | "cursor_y"
  | "history_all_bytes"
  | "history_bytes"
  | "history_limit"
  | "history_size"
  | "insert_flag"
  | "keypad_cursor_flag"
  | "keypad_flag"
  | "last_window_index"
  | "line"
  | "mouse_all_flag"
  | "mouse_any_flag"
  | "mouse_button_flag"
  | "mouse_sgr_flag"
  | "mouse_standard_flag"
  | "next_session_id"
  | "origin_flag"
  | "pane_active"
  | "pane_at_bottom"
  | "pane_at_left"
  | "pane_at_right"
  | "pane_at_top"
  | "pane_bg"
  | "pane_bottom"
  | "pane_current_command"
  | "pane_current_path"
  | "pane_dead"
  | "pane_dead_signal"
  | "pane_dead_status"
  | "pane_dead_time"
  | "pane_fg"
  | "pane_flags"
  | "pane_floating_flag"
  | "pane_format"
  | "pane_height"
  | "pane_id"
  | "pane_in_mode"
  | "pane_index"
  | "pane_input_off"
  | "pane_key_mode"
  | "pane_last"
  | "pane_left"
  | "pane_marked"
  | "pane_marked_set"
  | "pane_mode"
  | "pane_path"
  | "pane_pb_progress"
  | "pane_pb_state"
  | "pane_pid"
  | "pane_pipe"
  | "pane_pipe_pid"
  | "pane_right"
  | "pane_search_string"
  | "pane_start_command"
  | "pane_start_path"
  | "pane_synchronized"
  | "pane_tabs"
  | "pane_title"
  | "pane_top"
  | "pane_tty"
  | "pane_unseen_changes"
  | "pane_width"
  | "pane_x"
  | "pane_y"
  | "pane_z"
  | "pane_zoomed_flag"
  | "pid"
  | "scroll_position"
  | "scroll_region_lower"
  | "scroll_region_upper"
  | "search_match"
  | "selection_end_x"
  | "selection_end_y"
  | "selection_start_x"
  | "selection_start_y"
  | "session_active"
  | "session_activity"
  | "session_activity_flag"
  | "session_alert"
  | "session_alerts"
  | "session_attached"
  | "session_attached_list"
  | "session_bell_flag"
  | "session_created"
  | "session_format"
  | "session_group"
  | "session_group_attached"
  | "session_group_attached_list"
  | "session_group_list"
  | "session_group_many_attached"
  | "session_group_size"
  | "session_grouped"
  | "session_id"
  | "session_last_attached"
  | "session_many_attached"
  | "session_marked"
  | "session_name"
  | "session_path"
  | "session_silence_flag"
  | "session_stack"
  | "session_windows"
  | "socket_path"
  | "start_time"
  | "synchronized_output_flag"
  | "uid"
  | "user"
  | "version"
  | "window_active"
  | "window_active_clients"
  | "window_active_clients_list"
  | "window_active_sessions"
  | "window_active_sessions_list"
  | "window_activity"
  | "window_activity_flag"
  | "window_bell_flag"
  | "window_bigger"
  | "window_cell_height"
  | "window_cell_width"
  | "window_end_flag"
  | "window_flags"
  | "window_format"
  | "window_height"
  | "window_id"
  | "window_index"
  | "window_last_flag"
  | "window_layout"
  | "window_linked"
  | "window_linked_sessions"
  | "window_linked_sessions_list"
  | "window_marked_flag"
  | "window_name"
  | "window_offset_x"
  | "window_offset_y"
  | "window_panes"
  | "window_raw_flags"
  | "window_silence_flag"
  | "window_stack_index"
  | "window_start_flag"
  | "window_visible_layout"
  | "window_width"
  | "window_zoomed_flag"
  | "wrap_flag";

/** The shapes tmux writes that are not simply text. */
export type FormatValueType =
  | "boolean"
  | "number"
  | "pane-id"
  | "session-id"
  | "time"
  | "window-id";
export type FormatIdentityType = "pane-id" | "session-id" | "window-id";

/**
 * Which fields carry which shape.
 *
 * Derived from tmux's own format.c and held to a live server by
 * tests/integration/format_types.test.ts on every version CI runs.
 *
 * Local: `DecodedFormatValue` is what a caller needs.
 */
export type FormatValueTypes = {
  readonly active_window_index: "number";
  readonly alternate_on: "boolean";
  readonly alternate_saved_x: "number";
  readonly alternate_saved_y: "number";
  readonly bracket_paste_flag: "boolean";
  readonly buffer_size: "number";
  readonly client_activity: "time";
  readonly client_cell_height: "number";
  readonly client_cell_width: "number";
  readonly client_control_mode: "boolean";
  readonly client_created: "time";
  readonly client_discarded: "number";
  readonly client_height: "number";
  readonly client_pid: "number";
  readonly client_prefix: "boolean";
  readonly client_readonly: "boolean";
  readonly client_uid: "number";
  readonly client_utf8: "boolean";
  readonly client_width: "number";
  readonly client_written: "number";
  readonly copy_cursor_x: "number";
  readonly copy_cursor_y: "number";
  readonly cursor_blinking: "boolean";
  readonly cursor_flag: "boolean";
  readonly cursor_very_visible: "boolean";
  readonly cursor_x: "number";
  readonly cursor_y: "number";
  readonly history_bytes: "number";
  readonly history_limit: "number";
  readonly history_size: "number";
  readonly insert_flag: "boolean";
  readonly keypad_cursor_flag: "boolean";
  readonly keypad_flag: "boolean";
  readonly last_window_index: "number";
  readonly line: "number";
  readonly mouse_all_flag: "boolean";
  readonly mouse_any_flag: "boolean";
  readonly mouse_button_flag: "boolean";
  readonly mouse_sgr_flag: "boolean";
  readonly mouse_standard_flag: "boolean";
  readonly next_session_id: "session-id";
  readonly origin_flag: "boolean";
  readonly pane_active: "boolean";
  readonly pane_at_bottom: "boolean";
  readonly pane_at_left: "boolean";
  readonly pane_at_right: "boolean";
  readonly pane_at_top: "boolean";
  readonly pane_bottom: "number";
  readonly pane_dead: "boolean";
  readonly pane_dead_status: "number";
  readonly pane_dead_time: "time";
  readonly pane_floating_flag: "boolean";
  readonly pane_format: "boolean";
  readonly pane_height: "number";
  readonly pane_id: "pane-id";
  readonly pane_in_mode: "number";
  readonly pane_index: "number";
  readonly pane_input_off: "boolean";
  readonly pane_last: "boolean";
  readonly pane_left: "number";
  readonly pane_marked: "boolean";
  readonly pane_marked_set: "boolean";
  readonly pane_pb_progress: "number";
  readonly pane_pid: "number";
  readonly pane_pipe: "boolean";
  readonly pane_pipe_pid: "number";
  readonly pane_right: "number";
  readonly pane_synchronized: "boolean";
  readonly pane_top: "number";
  readonly pane_unseen_changes: "boolean";
  readonly pane_width: "number";
  readonly pane_x: "number";
  readonly pane_y: "number";
  readonly pane_z: "number";
  readonly pane_zoomed_flag: "boolean";
  readonly pid: "number";
  readonly scroll_position: "number";
  readonly scroll_region_lower: "number";
  readonly scroll_region_upper: "number";
  readonly selection_end_x: "number";
  readonly selection_end_y: "number";
  readonly selection_start_x: "number";
  readonly selection_start_y: "number";
  readonly session_active: "boolean";
  readonly session_activity: "time";
  readonly session_activity_flag: "boolean";
  readonly session_attached: "number";
  readonly session_bell_flag: "boolean";
  readonly session_created: "time";
  readonly session_format: "boolean";
  readonly session_group_attached: "number";
  readonly session_group_many_attached: "boolean";
  readonly session_group_size: "number";
  readonly session_grouped: "boolean";
  readonly session_id: "session-id";
  readonly session_last_attached: "time";
  readonly session_many_attached: "boolean";
  readonly session_marked: "boolean";
  readonly session_silence_flag: "boolean";
  readonly session_windows: "number";
  readonly start_time: "time";
  readonly synchronized_output_flag: "boolean";
  readonly uid: "number";
  readonly window_active: "boolean";
  readonly window_active_clients: "number";
  readonly window_active_sessions: "number";
  readonly window_activity: "time";
  readonly window_activity_flag: "boolean";
  readonly window_bell_flag: "boolean";
  readonly window_bigger: "boolean";
  readonly window_cell_height: "number";
  readonly window_cell_width: "number";
  readonly window_end_flag: "boolean";
  readonly window_format: "boolean";
  readonly window_height: "number";
  readonly window_id: "window-id";
  readonly window_index: "number";
  readonly window_last_flag: "boolean";
  readonly window_linked: "boolean";
  readonly window_linked_sessions: "number";
  readonly window_marked_flag: "boolean";
  readonly window_offset_x: "number";
  readonly window_offset_y: "number";
  readonly window_panes: "number";
  readonly window_silence_flag: "boolean";
  readonly window_stack_index: "number";
  readonly window_start_flag: "boolean";
  readonly window_width: "number";
  readonly window_zoomed_flag: "boolean";
  readonly wrap_flag: "boolean";
};

/** The raw text tmux writes, authenticated where it carries an identity. */
export type RawFormatValue<Token extends FormatFieldName> = Token extends keyof FormatValueTypes
  ? FormatValueTypes[Token] extends "pane-id"
    ? PaneId | ""
    : FormatValueTypes[Token] extends "session-id"
      ? SessionId | ""
      : FormatValueTypes[Token] extends "window-id"
        ? WindowId | ""
        : string
  : string;

/** What a caller reads for one field, once the text has been decoded. */
export type DecodedFormatValue<Token extends FormatFieldName> = Token extends keyof FormatValueTypes
  ? FormatValueTypes[Token] extends "pane-id"
    ? PaneId
    : FormatValueTypes[Token] extends "session-id"
      ? SessionId
      : FormatValueTypes[Token] extends "window-id"
        ? WindowId
        : FormatValueTypes[Token] extends "number"
          ? SafeInteger
          : FormatValueTypes[Token] extends "boolean"
            ? boolean
            : Date
  : string;

/** Idiomatic property names layered over a row, carrying decoded values. */
export type AliasedFields<Row, Aliases extends Readonly<Record<string, keyof Row>>> = {
  readonly [Key in keyof Aliases]: Aliases[Key] extends FormatFieldName
    ? null extends Row[Aliases[Key]]
      ? DecodedFormatValue<Aliases[Key]> | null
      : DecodedFormatValue<Aliases[Key]>
    : Row[Aliases[Key]];
};

/** A raw format row whose listed identity fields are present. */
export type RowWithIdentities<Identities extends FormatFieldName> = {
  readonly [Key in FormatFieldName]: Key extends Identities
    ? Exclude<RawFormatValue<Key>, "">
    : RawFormatValue<Key> | null;
};

export type SessionAliasMap = {
  readonly activeWindowIndex: "active_window_index";
  readonly configFiles: "config_files";
  readonly lastWindowIndex: "last_window_index";
  readonly line: "line";
  readonly nextSessionId: "next_session_id";
  readonly pid: "pid";
  readonly active: "session_active";
  readonly activity: "session_activity";
  readonly activityFlag: "session_activity_flag";
  readonly alert: "session_alert";
  readonly alerts: "session_alerts";
  readonly attached: "session_attached";
  readonly attachedList: "session_attached_list";
  readonly bellFlag: "session_bell_flag";
  readonly created: "session_created";
  readonly sessionFormat: "session_format";
  readonly group: "session_group";
  readonly groupAttached: "session_group_attached";
  readonly groupAttachedList: "session_group_attached_list";
  readonly groupList: "session_group_list";
  readonly groupManyAttached: "session_group_many_attached";
  readonly groupSize: "session_group_size";
  readonly grouped: "session_grouped";
  readonly id: "session_id";
  readonly lastAttached: "session_last_attached";
  readonly manyAttached: "session_many_attached";
  readonly marked: "session_marked";
  readonly name: "session_name";
  readonly path: "session_path";
  readonly silenceFlag: "session_silence_flag";
  readonly stack: "session_stack";
  readonly sessionWindows: "session_windows";
  readonly socketPath: "socket_path";
  readonly startTime: "start_time";
  readonly uid: "uid";
  readonly user: "user";
  readonly version: "version";
};

export type WindowAliasMap = {
  readonly configFiles: "config_files";
  readonly line: "line";
  readonly nextSessionId: "next_session_id";
  readonly pid: "pid";
  readonly socketPath: "socket_path";
  readonly startTime: "start_time";
  readonly uid: "uid";
  readonly user: "user";
  readonly version: "version";
  readonly active: "window_active";
  readonly activeClients: "window_active_clients";
  readonly activeClientsList: "window_active_clients_list";
  readonly activeSessions: "window_active_sessions";
  readonly activeSessionsList: "window_active_sessions_list";
  readonly activity: "window_activity";
  readonly activityFlag: "window_activity_flag";
  readonly bellFlag: "window_bell_flag";
  readonly bigger: "window_bigger";
  readonly cellHeight: "window_cell_height";
  readonly cellWidth: "window_cell_width";
  readonly endFlag: "window_end_flag";
  readonly flags: "window_flags";
  readonly windowFormat: "window_format";
  readonly height: "window_height";
  readonly id: "window_id";
  readonly index: "window_index";
  readonly lastFlag: "window_last_flag";
  readonly layout: "window_layout";
  readonly linked: "window_linked";
  readonly windowLinkedSessions: "window_linked_sessions";
  readonly linkedSessionsList: "window_linked_sessions_list";
  readonly markedFlag: "window_marked_flag";
  readonly name: "window_name";
  readonly offsetX: "window_offset_x";
  readonly offsetY: "window_offset_y";
  readonly windowPanes: "window_panes";
  readonly rawFlags: "window_raw_flags";
  readonly silenceFlag: "window_silence_flag";
  readonly stackIndex: "window_stack_index";
  readonly startFlag: "window_start_flag";
  readonly visibleLayout: "window_visible_layout";
  readonly width: "window_width";
  readonly zoomedFlag: "window_zoomed_flag";
};

export type PaneAliasMap = {
  readonly alternateOn: "alternate_on";
  readonly alternateSavedX: "alternate_saved_x";
  readonly alternateSavedY: "alternate_saved_y";
  readonly bracketPasteFlag: "bracket_paste_flag";
  readonly configFiles: "config_files";
  readonly cursorBlinking: "cursor_blinking";
  readonly cursorCharacter: "cursor_character";
  readonly cursorColour: "cursor_colour";
  readonly cursorFlag: "cursor_flag";
  readonly cursorShape: "cursor_shape";
  readonly cursorVeryVisible: "cursor_very_visible";
  readonly cursorX: "cursor_x";
  readonly cursorY: "cursor_y";
  readonly historyAllBytes: "history_all_bytes";
  readonly historyBytes: "history_bytes";
  readonly historyLimit: "history_limit";
  readonly historySize: "history_size";
  readonly insertFlag: "insert_flag";
  readonly keypadCursorFlag: "keypad_cursor_flag";
  readonly keypadFlag: "keypad_flag";
  readonly line: "line";
  readonly mouseAllFlag: "mouse_all_flag";
  readonly mouseAnyFlag: "mouse_any_flag";
  readonly mouseButtonFlag: "mouse_button_flag";
  readonly mouseSgrFlag: "mouse_sgr_flag";
  readonly mouseStandardFlag: "mouse_standard_flag";
  readonly nextSessionId: "next_session_id";
  readonly originFlag: "origin_flag";
  readonly active: "pane_active";
  readonly atBottom: "pane_at_bottom";
  readonly atLeft: "pane_at_left";
  readonly atRight: "pane_at_right";
  readonly atTop: "pane_at_top";
  readonly bg: "pane_bg";
  readonly bottom: "pane_bottom";
  readonly currentCommand: "pane_current_command";
  readonly currentPath: "pane_current_path";
  readonly dead: "pane_dead";
  readonly deadSignal: "pane_dead_signal";
  readonly deadStatus: "pane_dead_status";
  readonly deadTime: "pane_dead_time";
  readonly fg: "pane_fg";
  readonly flags: "pane_flags";
  readonly floatingFlag: "pane_floating_flag";
  readonly paneFormat: "pane_format";
  readonly height: "pane_height";
  readonly id: "pane_id";
  readonly inMode: "pane_in_mode";
  readonly index: "pane_index";
  readonly inputOff: "pane_input_off";
  readonly keyMode: "pane_key_mode";
  readonly last: "pane_last";
  readonly left: "pane_left";
  readonly marked: "pane_marked";
  readonly markedSet: "pane_marked_set";
  readonly mode: "pane_mode";
  readonly path: "pane_path";
  readonly pbProgress: "pane_pb_progress";
  readonly pbState: "pane_pb_state";
  readonly panePid: "pane_pid";
  readonly pipe: "pane_pipe";
  readonly pipePid: "pane_pipe_pid";
  readonly right: "pane_right";
  readonly searchString: "pane_search_string";
  readonly startCommand: "pane_start_command";
  readonly startPath: "pane_start_path";
  readonly synchronized: "pane_synchronized";
  readonly tabs: "pane_tabs";
  readonly title: "pane_title";
  readonly top: "pane_top";
  readonly tty: "pane_tty";
  readonly unseenChanges: "pane_unseen_changes";
  readonly width: "pane_width";
  readonly x: "pane_x";
  readonly y: "pane_y";
  readonly z: "pane_z";
  readonly zoomedFlag: "pane_zoomed_flag";
  readonly pid: "pid";
  readonly scrollRegionLower: "scroll_region_lower";
  readonly scrollRegionUpper: "scroll_region_upper";
  readonly socketPath: "socket_path";
  readonly startTime: "start_time";
  readonly synchronizedOutputFlag: "synchronized_output_flag";
  readonly uid: "uid";
  readonly user: "user";
  readonly version: "version";
  readonly wrapFlag: "wrap_flag";
};

export type ClientAliasMap = {
  readonly activity: "client_activity";
  readonly cellHeight: "client_cell_height";
  readonly cellWidth: "client_cell_width";
  readonly controlMode: "client_control_mode";
  readonly created: "client_created";
  readonly discarded: "client_discarded";
  readonly flags: "client_flags";
  readonly height: "client_height";
  readonly keyTable: "client_key_table";
  readonly lastSession: "client_last_session";
  readonly modeFormat: "client_mode_format";
  readonly name: "client_name";
  readonly clientPid: "client_pid";
  readonly prefix: "client_prefix";
  readonly readonly: "client_readonly";
  readonly clientSession: "client_session";
  readonly termfeatures: "client_termfeatures";
  readonly termname: "client_termname";
  readonly termtype: "client_termtype";
  readonly tty: "client_tty";
  readonly clientUid: "client_uid";
  readonly clientUser: "client_user";
  readonly utf8: "client_utf8";
  readonly width: "client_width";
  readonly written: "client_written";
  readonly configFiles: "config_files";
  readonly line: "line";
  readonly nextSessionId: "next_session_id";
  readonly pid: "pid";
  readonly socketPath: "socket_path";
  readonly startTime: "start_time";
  readonly uid: "uid";
  readonly user: "user";
  readonly version: "version";
};
