// Generated by scripts/generate-formats.ts. Do not edit.

import type { PaneId, SessionId, WindowId } from "../common.js";
import type { FormatFieldName } from "./format_field_names.js";

/** The shapes tmux writes that are not simply text. */
export type FormatValueType =
  | "boolean"
  | "number"
  | "pane-id"
  | "session-id"
  | "time"
  | "window-id";
export type FormatIdentityType = "pane-id" | "session-id" | "window-id";

/**
 * Which fields carry which shape.
 *
 * Derived from tmux's own format.c and held to a live server by
 * tests/integration/format_types.test.ts on every version CI runs.
 *
 * Local: `DecodedFormatValue` is what a caller needs.
 */
interface FormatValueTypes {
  readonly active_window_index: "number";
  readonly alternate_on: "boolean";
  readonly alternate_saved_x: "number";
  readonly alternate_saved_y: "number";
  readonly bracket_paste_flag: "boolean";
  readonly buffer_size: "number";
  readonly client_activity: "time";
  readonly client_cell_height: "number";
  readonly client_cell_width: "number";
  readonly client_control_mode: "boolean";
  readonly client_created: "time";
  readonly client_discarded: "number";
  readonly client_height: "number";
  readonly client_pid: "number";
  readonly client_prefix: "boolean";
  readonly client_readonly: "boolean";
  readonly client_uid: "number";
  readonly client_utf8: "boolean";
  readonly client_width: "number";
  readonly client_written: "number";
  readonly copy_cursor_x: "number";
  readonly copy_cursor_y: "number";
  readonly cursor_blinking: "boolean";
  readonly cursor_flag: "boolean";
  readonly cursor_very_visible: "boolean";
  readonly cursor_x: "number";
  readonly cursor_y: "number";
  readonly history_bytes: "number";
  readonly history_limit: "number";
  readonly history_size: "number";
  readonly insert_flag: "boolean";
  readonly keypad_cursor_flag: "boolean";
  readonly keypad_flag: "boolean";
  readonly last_window_index: "number";
  readonly line: "number";
  readonly mouse_all_flag: "boolean";
  readonly mouse_any_flag: "boolean";
  readonly mouse_button_flag: "boolean";
  readonly mouse_sgr_flag: "boolean";
  readonly mouse_standard_flag: "boolean";
  readonly next_session_id: "session-id";
  readonly origin_flag: "boolean";
  readonly pane_active: "boolean";
  readonly pane_at_bottom: "boolean";
  readonly pane_at_left: "boolean";
  readonly pane_at_right: "boolean";
  readonly pane_at_top: "boolean";
  readonly pane_bottom: "number";
  readonly pane_dead: "boolean";
  readonly pane_dead_status: "number";
  readonly pane_dead_time: "time";
  readonly pane_floating_flag: "boolean";
  readonly pane_format: "boolean";
  readonly pane_height: "number";
  readonly pane_id: "pane-id";
  readonly pane_in_mode: "number";
  readonly pane_index: "number";
  readonly pane_input_off: "boolean";
  readonly pane_last: "boolean";
  readonly pane_left: "number";
  readonly pane_marked: "boolean";
  readonly pane_marked_set: "boolean";
  readonly pane_pb_progress: "number";
  readonly pane_pid: "number";
  readonly pane_pipe: "boolean";
  readonly pane_pipe_pid: "number";
  readonly pane_right: "number";
  readonly pane_synchronized: "boolean";
  readonly pane_top: "number";
  readonly pane_unseen_changes: "boolean";
  readonly pane_width: "number";
  readonly pane_x: "number";
  readonly pane_y: "number";
  readonly pane_z: "number";
  readonly pane_zoomed_flag: "boolean";
  readonly pid: "number";
  readonly scroll_position: "number";
  readonly scroll_region_lower: "number";
  readonly scroll_region_upper: "number";
  readonly selection_end_x: "number";
  readonly selection_end_y: "number";
  readonly selection_start_x: "number";
  readonly selection_start_y: "number";
  readonly session_active: "boolean";
  readonly session_activity: "time";
  readonly session_activity_flag: "boolean";
  readonly session_attached: "number";
  readonly session_bell_flag: "boolean";
  readonly session_created: "time";
  readonly session_format: "boolean";
  readonly session_group_attached: "number";
  readonly session_group_many_attached: "boolean";
  readonly session_group_size: "number";
  readonly session_grouped: "boolean";
  readonly session_id: "session-id";
  readonly session_last_attached: "time";
  readonly session_many_attached: "boolean";
  readonly session_marked: "boolean";
  readonly session_silence_flag: "boolean";
  readonly session_windows: "number";
  readonly start_time: "time";
  readonly synchronized_output_flag: "boolean";
  readonly uid: "number";
  readonly window_active: "boolean";
  readonly window_active_clients: "number";
  readonly window_active_sessions: "number";
  readonly window_activity: "time";
  readonly window_activity_flag: "boolean";
  readonly window_bell_flag: "boolean";
  readonly window_bigger: "boolean";
  readonly window_cell_height: "number";
  readonly window_cell_width: "number";
  readonly window_end_flag: "boolean";
  readonly window_format: "boolean";
  readonly window_height: "number";
  readonly window_id: "window-id";
  readonly window_index: "number";
  readonly window_last_flag: "boolean";
  readonly window_linked: "boolean";
  readonly window_linked_sessions: "number";
  readonly window_marked_flag: "boolean";
  readonly window_offset_x: "number";
  readonly window_offset_y: "number";
  readonly window_panes: "number";
  readonly window_silence_flag: "boolean";
  readonly window_stack_index: "number";
  readonly window_start_flag: "boolean";
  readonly window_width: "number";
  readonly window_zoomed_flag: "boolean";
  readonly wrap_flag: "boolean";
}

/** The raw text tmux writes, authenticated where it carries an identity. */
export type RawFormatValue<Token extends FormatFieldName> = Token extends keyof FormatValueTypes
  ? FormatValueTypes[Token] extends "pane-id"
    ? PaneId | ""
    : FormatValueTypes[Token] extends "session-id"
      ? SessionId | ""
      : FormatValueTypes[Token] extends "window-id"
        ? WindowId | ""
        : string
  : string;

/** What a caller reads for one field, once the text has been decoded. */
export type DecodedFormatValue<Token extends FormatFieldName> = Token extends keyof FormatValueTypes
  ? FormatValueTypes[Token] extends "pane-id"
    ? PaneId
    : FormatValueTypes[Token] extends "session-id"
      ? SessionId
      : FormatValueTypes[Token] extends "window-id"
        ? WindowId
        : FormatValueTypes[Token] extends "number"
          ? number
          : FormatValueTypes[Token] extends "boolean"
            ? boolean
            : Date
  : string;

export const FORMAT_VALUE_TYPES: Readonly<FormatValueTypes> = Object.freeze({
  active_window_index: "number",
  alternate_on: "boolean",
  alternate_saved_x: "number",
  alternate_saved_y: "number",
  bracket_paste_flag: "boolean",
  buffer_size: "number",
  client_activity: "time",
  client_cell_height: "number",
  client_cell_width: "number",
  client_control_mode: "boolean",
  client_created: "time",
  client_discarded: "number",
  client_height: "number",
  client_pid: "number",
  client_prefix: "boolean",
  client_readonly: "boolean",
  client_uid: "number",
  client_utf8: "boolean",
  client_width: "number",
  client_written: "number",
  copy_cursor_x: "number",
  copy_cursor_y: "number",
  cursor_blinking: "boolean",
  cursor_flag: "boolean",
  cursor_very_visible: "boolean",
  cursor_x: "number",
  cursor_y: "number",
  history_bytes: "number",
  history_limit: "number",
  history_size: "number",
  insert_flag: "boolean",
  keypad_cursor_flag: "boolean",
  keypad_flag: "boolean",
  last_window_index: "number",
  line: "number",
  mouse_all_flag: "boolean",
  mouse_any_flag: "boolean",
  mouse_button_flag: "boolean",
  mouse_sgr_flag: "boolean",
  mouse_standard_flag: "boolean",
  next_session_id: "session-id",
  origin_flag: "boolean",
  pane_active: "boolean",
  pane_at_bottom: "boolean",
  pane_at_left: "boolean",
  pane_at_right: "boolean",
  pane_at_top: "boolean",
  pane_bottom: "number",
  pane_dead: "boolean",
  pane_dead_status: "number",
  pane_dead_time: "time",
  pane_floating_flag: "boolean",
  pane_format: "boolean",
  pane_height: "number",
  pane_id: "pane-id",
  pane_in_mode: "number",
  pane_index: "number",
  pane_input_off: "boolean",
  pane_last: "boolean",
  pane_left: "number",
  pane_marked: "boolean",
  pane_marked_set: "boolean",
  pane_pb_progress: "number",
  pane_pid: "number",
  pane_pipe: "boolean",
  pane_pipe_pid: "number",
  pane_right: "number",
  pane_synchronized: "boolean",
  pane_top: "number",
  pane_unseen_changes: "boolean",
  pane_width: "number",
  pane_x: "number",
  pane_y: "number",
  pane_z: "number",
  pane_zoomed_flag: "boolean",
  pid: "number",
  scroll_position: "number",
  scroll_region_lower: "number",
  scroll_region_upper: "number",
  selection_end_x: "number",
  selection_end_y: "number",
  selection_start_x: "number",
  selection_start_y: "number",
  session_active: "boolean",
  session_activity: "time",
  session_activity_flag: "boolean",
  session_attached: "number",
  session_bell_flag: "boolean",
  session_created: "time",
  session_format: "boolean",
  session_group_attached: "number",
  session_group_many_attached: "boolean",
  session_group_size: "number",
  session_grouped: "boolean",
  session_id: "session-id",
  session_last_attached: "time",
  session_many_attached: "boolean",
  session_marked: "boolean",
  session_silence_flag: "boolean",
  session_windows: "number",
  start_time: "time",
  synchronized_output_flag: "boolean",
  uid: "number",
  window_active: "boolean",
  window_active_clients: "number",
  window_active_sessions: "number",
  window_activity: "time",
  window_activity_flag: "boolean",
  window_bell_flag: "boolean",
  window_bigger: "boolean",
  window_cell_height: "number",
  window_cell_width: "number",
  window_end_flag: "boolean",
  window_format: "boolean",
  window_height: "number",
  window_id: "window-id",
  window_index: "number",
  window_last_flag: "boolean",
  window_linked: "boolean",
  window_linked_sessions: "number",
  window_marked_flag: "boolean",
  window_offset_x: "number",
  window_offset_y: "number",
  window_panes: "number",
  window_silence_flag: "boolean",
  window_stack_index: "number",
  window_start_flag: "boolean",
  window_width: "number",
  window_zoomed_flag: "boolean",
  wrap_flag: "boolean",
});

/** Look up a typed field without widening the generated key set. */
export function formatValueType(token: string): FormatValueType | undefined {
  return FORMAT_VALUE_TYPES[token as keyof typeof FORMAT_VALUE_TYPES];
}

export const FORMAT_IDENTITY_FIELDS: readonly Readonly<{
  token: FormatFieldName;
  type: FormatIdentityType;
}>[] = Object.freeze([
  Object.freeze({ token: "next_session_id", type: "session-id" }),
  Object.freeze({ token: "pane_id", type: "pane-id" }),
  Object.freeze({ token: "session_id", type: "session-id" }),
  Object.freeze({ token: "window_id", type: "window-id" }),
]);
