// Generated by scripts/generate-formats.ts. Do not edit.

import type { FormatFieldName } from "./format_field_names.js";
import type { FormatValueType } from "../field_types.js";

export type WhereModel = "client" | "pane" | "session" | "window";

export interface WhereField {
  /** The camelCase key a caller writes in criteria. */
  readonly criteriaName: string;
  readonly domain: FormatValueType | "string";
  /**
   * The first tmux release that has this field.
   *
   * A server older than this does not answer for it at all, so a query naming
   * it is refused rather than matched against nothing — which reads as "no
   * object has this" and is a different statement.
   */
  readonly since: string;
  readonly token: FormatFieldName;
  /** The stable serialized name, unchanged across releases. */
  readonly wireName: string;
}

const sessionFields: readonly WhereField[] = Object.freeze([
  Object.freeze({
    criteriaName: "activeWindowIndex",
    domain: "number",
    since: "3.2a",
    token: "active_window_index",
    wireName: "active_window_index",
  }),
  Object.freeze({
    criteriaName: "lastWindowIndex",
    domain: "number",
    since: "3.2a",
    token: "last_window_index",
    wireName: "last_window_index",
  }),
  Object.freeze({
    criteriaName: "name",
    domain: "string",
    since: "3.2a",
    token: "session_name",
    wireName: "name",
  }),
  Object.freeze({
    criteriaName: "active",
    domain: "boolean",
    since: "3.6",
    token: "session_active",
    wireName: "session_active",
  }),
  Object.freeze({
    criteriaName: "activity",
    domain: "time",
    since: "3.2a",
    token: "session_activity",
    wireName: "session_activity",
  }),
  Object.freeze({
    criteriaName: "activityFlag",
    domain: "boolean",
    since: "3.6",
    token: "session_activity_flag",
    wireName: "session_activity_flag",
  }),
  Object.freeze({
    criteriaName: "alert",
    domain: "string",
    since: "3.6",
    token: "session_alert",
    wireName: "session_alert",
  }),
  Object.freeze({
    criteriaName: "alerts",
    domain: "string",
    since: "3.2a",
    token: "session_alerts",
    wireName: "session_alerts",
  }),
  Object.freeze({
    criteriaName: "attached",
    domain: "number",
    since: "3.2a",
    token: "session_attached",
    wireName: "session_attached",
  }),
  Object.freeze({
    criteriaName: "attachedList",
    domain: "string",
    since: "3.2a",
    token: "session_attached_list",
    wireName: "session_attached_list",
  }),
  Object.freeze({
    criteriaName: "bellFlag",
    domain: "boolean",
    since: "3.6",
    token: "session_bell_flag",
    wireName: "session_bell_flag",
  }),
  Object.freeze({
    criteriaName: "created",
    domain: "time",
    since: "3.2a",
    token: "session_created",
    wireName: "session_created",
  }),
  Object.freeze({
    criteriaName: "format",
    domain: "boolean",
    since: "3.2a",
    token: "session_format",
    wireName: "session_format",
  }),
  Object.freeze({
    criteriaName: "group",
    domain: "string",
    since: "3.2a",
    token: "session_group",
    wireName: "session_group",
  }),
  Object.freeze({
    criteriaName: "groupAttached",
    domain: "number",
    since: "3.2a",
    token: "session_group_attached",
    wireName: "session_group_attached",
  }),
  Object.freeze({
    criteriaName: "groupAttachedList",
    domain: "string",
    since: "3.2a",
    token: "session_group_attached_list",
    wireName: "session_group_attached_list",
  }),
  Object.freeze({
    criteriaName: "groupList",
    domain: "string",
    since: "3.2a",
    token: "session_group_list",
    wireName: "session_group_list",
  }),
  Object.freeze({
    criteriaName: "groupManyAttached",
    domain: "boolean",
    since: "3.2a",
    token: "session_group_many_attached",
    wireName: "session_group_many_attached",
  }),
  Object.freeze({
    criteriaName: "groupSize",
    domain: "number",
    since: "3.2a",
    token: "session_group_size",
    wireName: "session_group_size",
  }),
  Object.freeze({
    criteriaName: "grouped",
    domain: "boolean",
    since: "3.2a",
    token: "session_grouped",
    wireName: "session_grouped",
  }),
  Object.freeze({
    criteriaName: "id",
    domain: "session-id",
    since: "3.2a",
    token: "session_id",
    wireName: "session_id",
  }),
  Object.freeze({
    criteriaName: "lastAttached",
    domain: "time",
    since: "3.2a",
    token: "session_last_attached",
    wireName: "session_last_attached",
  }),
  Object.freeze({
    criteriaName: "manyAttached",
    domain: "boolean",
    since: "3.2a",
    token: "session_many_attached",
    wireName: "session_many_attached",
  }),
  Object.freeze({
    criteriaName: "marked",
    domain: "boolean",
    since: "3.2a",
    token: "session_marked",
    wireName: "session_marked",
  }),
  Object.freeze({
    criteriaName: "path",
    domain: "string",
    since: "3.2a",
    token: "session_path",
    wireName: "session_path",
  }),
  Object.freeze({
    criteriaName: "silenceFlag",
    domain: "boolean",
    since: "3.6",
    token: "session_silence_flag",
    wireName: "session_silence_flag",
  }),
  Object.freeze({
    criteriaName: "stack",
    domain: "string",
    since: "3.2a",
    token: "session_stack",
    wireName: "session_stack",
  }),
  Object.freeze({
    criteriaName: "sessionWindows",
    domain: "number",
    since: "3.2a",
    token: "session_windows",
    wireName: "session_windows",
  }),
]);

const windowFields: readonly WhereField[] = Object.freeze([
  Object.freeze({
    criteriaName: "name",
    domain: "string",
    since: "3.2a",
    token: "window_name",
    wireName: "name",
  }),
  Object.freeze({
    criteriaName: "active",
    domain: "boolean",
    since: "3.2a",
    token: "window_active",
    wireName: "window_active",
  }),
  Object.freeze({
    criteriaName: "activeClients",
    domain: "number",
    since: "3.2a",
    token: "window_active_clients",
    wireName: "window_active_clients",
  }),
  Object.freeze({
    criteriaName: "activeClientsList",
    domain: "string",
    since: "3.2a",
    token: "window_active_clients_list",
    wireName: "window_active_clients_list",
  }),
  Object.freeze({
    criteriaName: "activeSessions",
    domain: "number",
    since: "3.2a",
    token: "window_active_sessions",
    wireName: "window_active_sessions",
  }),
  Object.freeze({
    criteriaName: "activeSessionsList",
    domain: "string",
    since: "3.2a",
    token: "window_active_sessions_list",
    wireName: "window_active_sessions_list",
  }),
  Object.freeze({
    criteriaName: "activity",
    domain: "time",
    since: "3.2a",
    token: "window_activity",
    wireName: "window_activity",
  }),
  Object.freeze({
    criteriaName: "activityFlag",
    domain: "boolean",
    since: "3.2a",
    token: "window_activity_flag",
    wireName: "window_activity_flag",
  }),
  Object.freeze({
    criteriaName: "bellFlag",
    domain: "boolean",
    since: "3.2a",
    token: "window_bell_flag",
    wireName: "window_bell_flag",
  }),
  Object.freeze({
    criteriaName: "bigger",
    domain: "boolean",
    since: "3.2a",
    token: "window_bigger",
    wireName: "window_bigger",
  }),
  Object.freeze({
    criteriaName: "cellHeight",
    domain: "number",
    since: "3.2a",
    token: "window_cell_height",
    wireName: "window_cell_height",
  }),
  Object.freeze({
    criteriaName: "cellWidth",
    domain: "number",
    since: "3.2a",
    token: "window_cell_width",
    wireName: "window_cell_width",
  }),
  Object.freeze({
    criteriaName: "endFlag",
    domain: "boolean",
    since: "3.2a",
    token: "window_end_flag",
    wireName: "window_end_flag",
  }),
  Object.freeze({
    criteriaName: "flags",
    domain: "string",
    since: "3.2a",
    token: "window_flags",
    wireName: "window_flags",
  }),
  Object.freeze({
    criteriaName: "format",
    domain: "boolean",
    since: "3.2a",
    token: "window_format",
    wireName: "window_format",
  }),
  Object.freeze({
    criteriaName: "height",
    domain: "number",
    since: "3.2a",
    token: "window_height",
    wireName: "window_height",
  }),
  Object.freeze({
    criteriaName: "id",
    domain: "window-id",
    since: "3.2a",
    token: "window_id",
    wireName: "window_id",
  }),
  Object.freeze({
    criteriaName: "index",
    domain: "number",
    since: "3.2a",
    token: "window_index",
    wireName: "window_index",
  }),
  Object.freeze({
    criteriaName: "lastFlag",
    domain: "boolean",
    since: "3.2a",
    token: "window_last_flag",
    wireName: "window_last_flag",
  }),
  Object.freeze({
    criteriaName: "layout",
    domain: "string",
    since: "3.2a",
    token: "window_layout",
    wireName: "window_layout",
  }),
  Object.freeze({
    criteriaName: "linked",
    domain: "boolean",
    since: "3.2a",
    token: "window_linked",
    wireName: "window_linked",
  }),
  Object.freeze({
    criteriaName: "windowLinkedSessions",
    domain: "number",
    since: "3.2a",
    token: "window_linked_sessions",
    wireName: "window_linked_sessions",
  }),
  Object.freeze({
    criteriaName: "linkedSessionsList",
    domain: "string",
    since: "3.2a",
    token: "window_linked_sessions_list",
    wireName: "window_linked_sessions_list",
  }),
  Object.freeze({
    criteriaName: "markedFlag",
    domain: "boolean",
    since: "3.2a",
    token: "window_marked_flag",
    wireName: "window_marked_flag",
  }),
  Object.freeze({
    criteriaName: "offsetX",
    domain: "number",
    since: "3.2a",
    token: "window_offset_x",
    wireName: "window_offset_x",
  }),
  Object.freeze({
    criteriaName: "offsetY",
    domain: "number",
    since: "3.2a",
    token: "window_offset_y",
    wireName: "window_offset_y",
  }),
  Object.freeze({
    criteriaName: "windowPanes",
    domain: "number",
    since: "3.2a",
    token: "window_panes",
    wireName: "window_panes",
  }),
  Object.freeze({
    criteriaName: "rawFlags",
    domain: "string",
    since: "3.2a",
    token: "window_raw_flags",
    wireName: "window_raw_flags",
  }),
  Object.freeze({
    criteriaName: "silenceFlag",
    domain: "boolean",
    since: "3.2a",
    token: "window_silence_flag",
    wireName: "window_silence_flag",
  }),
  Object.freeze({
    criteriaName: "stackIndex",
    domain: "number",
    since: "3.2a",
    token: "window_stack_index",
    wireName: "window_stack_index",
  }),
  Object.freeze({
    criteriaName: "startFlag",
    domain: "boolean",
    since: "3.2a",
    token: "window_start_flag",
    wireName: "window_start_flag",
  }),
  Object.freeze({
    criteriaName: "visibleLayout",
    domain: "string",
    since: "3.2a",
    token: "window_visible_layout",
    wireName: "window_visible_layout",
  }),
  Object.freeze({
    criteriaName: "width",
    domain: "number",
    since: "3.2a",
    token: "window_width",
    wireName: "window_width",
  }),
  Object.freeze({
    criteriaName: "zoomedFlag",
    domain: "boolean",
    since: "3.2a",
    token: "window_zoomed_flag",
    wireName: "window_zoomed_flag",
  }),
]);

const paneFields: readonly WhereField[] = Object.freeze([
  Object.freeze({
    criteriaName: "alternateOn",
    domain: "boolean",
    since: "3.2a",
    token: "alternate_on",
    wireName: "alternate_on",
  }),
  Object.freeze({
    criteriaName: "alternateSavedX",
    domain: "number",
    since: "3.2a",
    token: "alternate_saved_x",
    wireName: "alternate_saved_x",
  }),
  Object.freeze({
    criteriaName: "alternateSavedY",
    domain: "number",
    since: "3.2a",
    token: "alternate_saved_y",
    wireName: "alternate_saved_y",
  }),
  Object.freeze({
    criteriaName: "bracketPasteFlag",
    domain: "boolean",
    since: "3.7",
    token: "bracket_paste_flag",
    wireName: "bracket_paste_flag",
  }),
  Object.freeze({
    criteriaName: "cursorBlinking",
    domain: "boolean",
    since: "3.6",
    token: "cursor_blinking",
    wireName: "cursor_blinking",
  }),
  Object.freeze({
    criteriaName: "cursorCharacter",
    domain: "string",
    since: "3.2a",
    token: "cursor_character",
    wireName: "cursor_character",
  }),
  Object.freeze({
    criteriaName: "cursorColour",
    domain: "string",
    since: "3.6",
    token: "cursor_colour",
    wireName: "cursor_colour",
  }),
  Object.freeze({
    criteriaName: "cursorFlag",
    domain: "boolean",
    since: "3.2a",
    token: "cursor_flag",
    wireName: "cursor_flag",
  }),
  Object.freeze({
    criteriaName: "cursorShape",
    domain: "string",
    since: "3.6",
    token: "cursor_shape",
    wireName: "cursor_shape",
  }),
  Object.freeze({
    criteriaName: "cursorVeryVisible",
    domain: "boolean",
    since: "3.6",
    token: "cursor_very_visible",
    wireName: "cursor_very_visible",
  }),
  Object.freeze({
    criteriaName: "cursorX",
    domain: "number",
    since: "3.2a",
    token: "cursor_x",
    wireName: "cursor_x",
  }),
  Object.freeze({
    criteriaName: "cursorY",
    domain: "number",
    since: "3.2a",
    token: "cursor_y",
    wireName: "cursor_y",
  }),
  Object.freeze({
    criteriaName: "historyAllBytes",
    domain: "string",
    since: "3.2a",
    token: "history_all_bytes",
    wireName: "history_all_bytes",
  }),
  Object.freeze({
    criteriaName: "historyBytes",
    domain: "number",
    since: "3.2a",
    token: "history_bytes",
    wireName: "history_bytes",
  }),
  Object.freeze({
    criteriaName: "historyLimit",
    domain: "number",
    since: "3.2a",
    token: "history_limit",
    wireName: "history_limit",
  }),
  Object.freeze({
    criteriaName: "historySize",
    domain: "number",
    since: "3.2a",
    token: "history_size",
    wireName: "history_size",
  }),
  Object.freeze({
    criteriaName: "insertFlag",
    domain: "boolean",
    since: "3.2a",
    token: "insert_flag",
    wireName: "insert_flag",
  }),
  Object.freeze({
    criteriaName: "keypadCursorFlag",
    domain: "boolean",
    since: "3.2a",
    token: "keypad_cursor_flag",
    wireName: "keypad_cursor_flag",
  }),
  Object.freeze({
    criteriaName: "keypadFlag",
    domain: "boolean",
    since: "3.2a",
    token: "keypad_flag",
    wireName: "keypad_flag",
  }),
  Object.freeze({
    criteriaName: "mouseAllFlag",
    domain: "boolean",
    since: "3.2a",
    token: "mouse_all_flag",
    wireName: "mouse_all_flag",
  }),
  Object.freeze({
    criteriaName: "mouseAnyFlag",
    domain: "boolean",
    since: "3.2a",
    token: "mouse_any_flag",
    wireName: "mouse_any_flag",
  }),
  Object.freeze({
    criteriaName: "mouseButtonFlag",
    domain: "boolean",
    since: "3.2a",
    token: "mouse_button_flag",
    wireName: "mouse_button_flag",
  }),
  Object.freeze({
    criteriaName: "mouseSgrFlag",
    domain: "boolean",
    since: "3.2a",
    token: "mouse_sgr_flag",
    wireName: "mouse_sgr_flag",
  }),
  Object.freeze({
    criteriaName: "mouseStandardFlag",
    domain: "boolean",
    since: "3.2a",
    token: "mouse_standard_flag",
    wireName: "mouse_standard_flag",
  }),
  Object.freeze({
    criteriaName: "originFlag",
    domain: "boolean",
    since: "3.2a",
    token: "origin_flag",
    wireName: "origin_flag",
  }),
  Object.freeze({
    criteriaName: "active",
    domain: "boolean",
    since: "3.2a",
    token: "pane_active",
    wireName: "pane_active",
  }),
  Object.freeze({
    criteriaName: "atBottom",
    domain: "boolean",
    since: "3.2a",
    token: "pane_at_bottom",
    wireName: "pane_at_bottom",
  }),
  Object.freeze({
    criteriaName: "atLeft",
    domain: "boolean",
    since: "3.2a",
    token: "pane_at_left",
    wireName: "pane_at_left",
  }),
  Object.freeze({
    criteriaName: "atRight",
    domain: "boolean",
    since: "3.2a",
    token: "pane_at_right",
    wireName: "pane_at_right",
  }),
  Object.freeze({
    criteriaName: "atTop",
    domain: "boolean",
    since: "3.2a",
    token: "pane_at_top",
    wireName: "pane_at_top",
  }),
  Object.freeze({
    criteriaName: "bg",
    domain: "string",
    since: "3.2a",
    token: "pane_bg",
    wireName: "pane_bg",
  }),
  Object.freeze({
    criteriaName: "bottom",
    domain: "number",
    since: "3.2a",
    token: "pane_bottom",
    wireName: "pane_bottom",
  }),
  Object.freeze({
    criteriaName: "currentCommand",
    domain: "string",
    since: "3.2a",
    token: "pane_current_command",
    wireName: "pane_current_command",
  }),
  Object.freeze({
    criteriaName: "currentPath",
    domain: "string",
    since: "3.2a",
    token: "pane_current_path",
    wireName: "pane_current_path",
  }),
  Object.freeze({
    criteriaName: "dead",
    domain: "boolean",
    since: "3.2a",
    token: "pane_dead",
    wireName: "pane_dead",
  }),
  Object.freeze({
    criteriaName: "deadSignal",
    domain: "string",
    since: "3.3",
    token: "pane_dead_signal",
    wireName: "pane_dead_signal",
  }),
  Object.freeze({
    criteriaName: "deadStatus",
    domain: "number",
    since: "3.2a",
    token: "pane_dead_status",
    wireName: "pane_dead_status",
  }),
  Object.freeze({
    criteriaName: "deadTime",
    domain: "time",
    since: "3.3",
    token: "pane_dead_time",
    wireName: "pane_dead_time",
  }),
  Object.freeze({
    criteriaName: "fg",
    domain: "string",
    since: "3.2a",
    token: "pane_fg",
    wireName: "pane_fg",
  }),
  Object.freeze({
    criteriaName: "flags",
    domain: "string",
    since: "3.7",
    token: "pane_flags",
    wireName: "pane_flags",
  }),
  Object.freeze({
    criteriaName: "floatingFlag",
    domain: "boolean",
    since: "3.7",
    token: "pane_floating_flag",
    wireName: "pane_floating_flag",
  }),
  Object.freeze({
    criteriaName: "format",
    domain: "boolean",
    since: "3.2a",
    token: "pane_format",
    wireName: "pane_format",
  }),
  Object.freeze({
    criteriaName: "height",
    domain: "number",
    since: "3.2a",
    token: "pane_height",
    wireName: "pane_height",
  }),
  Object.freeze({
    criteriaName: "id",
    domain: "pane-id",
    since: "3.2a",
    token: "pane_id",
    wireName: "pane_id",
  }),
  Object.freeze({
    criteriaName: "inMode",
    domain: "number",
    since: "3.2a",
    token: "pane_in_mode",
    wireName: "pane_in_mode",
  }),
  Object.freeze({
    criteriaName: "index",
    domain: "number",
    since: "3.2a",
    token: "pane_index",
    wireName: "pane_index",
  }),
  Object.freeze({
    criteriaName: "inputOff",
    domain: "boolean",
    since: "3.2a",
    token: "pane_input_off",
    wireName: "pane_input_off",
  }),
  Object.freeze({
    criteriaName: "keyMode",
    domain: "string",
    since: "3.5",
    token: "pane_key_mode",
    wireName: "pane_key_mode",
  }),
  Object.freeze({
    criteriaName: "last",
    domain: "boolean",
    since: "3.2a",
    token: "pane_last",
    wireName: "pane_last",
  }),
  Object.freeze({
    criteriaName: "left",
    domain: "number",
    since: "3.2a",
    token: "pane_left",
    wireName: "pane_left",
  }),
  Object.freeze({
    criteriaName: "marked",
    domain: "boolean",
    since: "3.2a",
    token: "pane_marked",
    wireName: "pane_marked",
  }),
  Object.freeze({
    criteriaName: "markedSet",
    domain: "boolean",
    since: "3.2a",
    token: "pane_marked_set",
    wireName: "pane_marked_set",
  }),
  Object.freeze({
    criteriaName: "mode",
    domain: "string",
    since: "3.2a",
    token: "pane_mode",
    wireName: "pane_mode",
  }),
  Object.freeze({
    criteriaName: "path",
    domain: "string",
    since: "3.2a",
    token: "pane_path",
    wireName: "pane_path",
  }),
  Object.freeze({
    criteriaName: "pbProgress",
    domain: "number",
    since: "3.7",
    token: "pane_pb_progress",
    wireName: "pane_pb_progress",
  }),
  Object.freeze({
    criteriaName: "pbState",
    domain: "string",
    since: "3.7",
    token: "pane_pb_state",
    wireName: "pane_pb_state",
  }),
  Object.freeze({
    criteriaName: "pid",
    domain: "number",
    since: "3.2a",
    token: "pane_pid",
    wireName: "pane_pid",
  }),
  Object.freeze({
    criteriaName: "pipe",
    domain: "boolean",
    since: "3.2a",
    token: "pane_pipe",
    wireName: "pane_pipe",
  }),
  Object.freeze({
    criteriaName: "pipePid",
    domain: "number",
    since: "3.7",
    token: "pane_pipe_pid",
    wireName: "pane_pipe_pid",
  }),
  Object.freeze({
    criteriaName: "right",
    domain: "number",
    since: "3.2a",
    token: "pane_right",
    wireName: "pane_right",
  }),
  Object.freeze({
    criteriaName: "searchString",
    domain: "string",
    since: "3.2a",
    token: "pane_search_string",
    wireName: "pane_search_string",
  }),
  Object.freeze({
    criteriaName: "startCommand",
    domain: "string",
    since: "3.2a",
    token: "pane_start_command",
    wireName: "pane_start_command",
  }),
  Object.freeze({
    criteriaName: "startPath",
    domain: "string",
    since: "3.2a",
    token: "pane_start_path",
    wireName: "pane_start_path",
  }),
  Object.freeze({
    criteriaName: "synchronized",
    domain: "boolean",
    since: "3.2a",
    token: "pane_synchronized",
    wireName: "pane_synchronized",
  }),
  Object.freeze({
    criteriaName: "tabs",
    domain: "string",
    since: "3.2a",
    token: "pane_tabs",
    wireName: "pane_tabs",
  }),
  Object.freeze({
    criteriaName: "title",
    domain: "string",
    since: "3.2a",
    token: "pane_title",
    wireName: "pane_title",
  }),
  Object.freeze({
    criteriaName: "top",
    domain: "number",
    since: "3.2a",
    token: "pane_top",
    wireName: "pane_top",
  }),
  Object.freeze({
    criteriaName: "tty",
    domain: "string",
    since: "3.2a",
    token: "pane_tty",
    wireName: "pane_tty",
  }),
  Object.freeze({
    criteriaName: "unseenChanges",
    domain: "boolean",
    since: "3.4",
    token: "pane_unseen_changes",
    wireName: "pane_unseen_changes",
  }),
  Object.freeze({
    criteriaName: "width",
    domain: "number",
    since: "3.2a",
    token: "pane_width",
    wireName: "pane_width",
  }),
  Object.freeze({
    criteriaName: "x",
    domain: "number",
    since: "3.7",
    token: "pane_x",
    wireName: "pane_x",
  }),
  Object.freeze({
    criteriaName: "y",
    domain: "number",
    since: "3.7",
    token: "pane_y",
    wireName: "pane_y",
  }),
  Object.freeze({
    criteriaName: "z",
    domain: "number",
    since: "3.7",
    token: "pane_z",
    wireName: "pane_z",
  }),
  Object.freeze({
    criteriaName: "zoomedFlag",
    domain: "boolean",
    since: "3.7",
    token: "pane_zoomed_flag",
    wireName: "pane_zoomed_flag",
  }),
  Object.freeze({
    criteriaName: "scrollRegionLower",
    domain: "number",
    since: "3.2a",
    token: "scroll_region_lower",
    wireName: "scroll_region_lower",
  }),
  Object.freeze({
    criteriaName: "scrollRegionUpper",
    domain: "number",
    since: "3.2a",
    token: "scroll_region_upper",
    wireName: "scroll_region_upper",
  }),
  Object.freeze({
    criteriaName: "synchronizedOutputFlag",
    domain: "boolean",
    since: "3.7",
    token: "synchronized_output_flag",
    wireName: "synchronized_output_flag",
  }),
  Object.freeze({
    criteriaName: "wrapFlag",
    domain: "boolean",
    since: "3.2a",
    token: "wrap_flag",
    wireName: "wrap_flag",
  }),
]);

const clientFields: readonly WhereField[] = Object.freeze([
  Object.freeze({
    criteriaName: "activity",
    domain: "time",
    since: "3.2a",
    token: "client_activity",
    wireName: "client_activity",
  }),
  Object.freeze({
    criteriaName: "cellHeight",
    domain: "number",
    since: "3.2a",
    token: "client_cell_height",
    wireName: "client_cell_height",
  }),
  Object.freeze({
    criteriaName: "cellWidth",
    domain: "number",
    since: "3.2a",
    token: "client_cell_width",
    wireName: "client_cell_width",
  }),
  Object.freeze({
    criteriaName: "controlMode",
    domain: "boolean",
    since: "3.2a",
    token: "client_control_mode",
    wireName: "client_control_mode",
  }),
  Object.freeze({
    criteriaName: "created",
    domain: "time",
    since: "3.2a",
    token: "client_created",
    wireName: "client_created",
  }),
  Object.freeze({
    criteriaName: "discarded",
    domain: "number",
    since: "3.2a",
    token: "client_discarded",
    wireName: "client_discarded",
  }),
  Object.freeze({
    criteriaName: "flags",
    domain: "string",
    since: "3.2a",
    token: "client_flags",
    wireName: "client_flags",
  }),
  Object.freeze({
    criteriaName: "height",
    domain: "number",
    since: "3.2a",
    token: "client_height",
    wireName: "client_height",
  }),
  Object.freeze({
    criteriaName: "keyTable",
    domain: "string",
    since: "3.2a",
    token: "client_key_table",
    wireName: "client_key_table",
  }),
  Object.freeze({
    criteriaName: "lastSession",
    domain: "string",
    since: "3.2a",
    token: "client_last_session",
    wireName: "client_last_session",
  }),
  Object.freeze({
    criteriaName: "modeFormat",
    domain: "string",
    since: "3.2a",
    token: "client_mode_format",
    wireName: "client_mode_format",
  }),
  Object.freeze({
    criteriaName: "name",
    domain: "string",
    since: "3.2a",
    token: "client_name",
    wireName: "client_name",
  }),
  Object.freeze({
    criteriaName: "pid",
    domain: "number",
    since: "3.2a",
    token: "client_pid",
    wireName: "client_pid",
  }),
  Object.freeze({
    criteriaName: "prefix",
    domain: "boolean",
    since: "3.2a",
    token: "client_prefix",
    wireName: "client_prefix",
  }),
  Object.freeze({
    criteriaName: "readonly",
    domain: "boolean",
    since: "3.2a",
    token: "client_readonly",
    wireName: "client_readonly",
  }),
  Object.freeze({
    criteriaName: "clientSession",
    domain: "string",
    since: "3.2a",
    token: "client_session",
    wireName: "client_session",
  }),
  Object.freeze({
    criteriaName: "termfeatures",
    domain: "string",
    since: "3.2a",
    token: "client_termfeatures",
    wireName: "client_termfeatures",
  }),
  Object.freeze({
    criteriaName: "termname",
    domain: "string",
    since: "3.2a",
    token: "client_termname",
    wireName: "client_termname",
  }),
  Object.freeze({
    criteriaName: "termtype",
    domain: "string",
    since: "3.2a",
    token: "client_termtype",
    wireName: "client_termtype",
  }),
  Object.freeze({
    criteriaName: "tty",
    domain: "string",
    since: "3.2a",
    token: "client_tty",
    wireName: "client_tty",
  }),
  Object.freeze({
    criteriaName: "uid",
    domain: "number",
    since: "3.2a",
    token: "client_uid",
    wireName: "client_uid",
  }),
  Object.freeze({
    criteriaName: "user",
    domain: "string",
    since: "3.2a",
    token: "client_user",
    wireName: "client_user",
  }),
  Object.freeze({
    criteriaName: "utf8",
    domain: "boolean",
    since: "3.2a",
    token: "client_utf8",
    wireName: "client_utf8",
  }),
  Object.freeze({
    criteriaName: "width",
    domain: "number",
    since: "3.2a",
    token: "client_width",
    wireName: "client_width",
  }),
  Object.freeze({
    criteriaName: "written",
    domain: "number",
    since: "3.2a",
    token: "client_written",
    wireName: "client_written",
  }),
]);

const emptyAliases: Readonly<Record<string, string>> = Object.freeze({});

export const WHERE_FIELDS_V1: Readonly<Record<WhereModel, readonly WhereField[]>> = Object.freeze({
  session: sessionFields,
  window: windowFields,
  pane: paneFields,
  client: clientFields,
});

export const WHERE_ALIASES_V1: Readonly<Record<WhereModel, Readonly<Record<string, string>>>> =
  Object.freeze({
    session: emptyAliases,
    window: emptyAliases,
    pane: emptyAliases,
    client: emptyAliases,
  });

export interface WhereRelation {
  readonly cardinality: "many" | "one";
  readonly name: string;
  readonly targetModel: WhereModel;
}

export const WHERE_RELATIONS_V1: Readonly<{
  readonly client: readonly [
    {
      readonly cardinality: "one";
      readonly name: "session";
      readonly targetModel: "session";
    },
    {
      readonly cardinality: "one";
      readonly name: "window";
      readonly targetModel: "window";
    },
    {
      readonly cardinality: "one";
      readonly name: "pane";
      readonly targetModel: "pane";
    },
  ];
  readonly pane: readonly [
    {
      readonly cardinality: "one";
      readonly name: "window";
      readonly targetModel: "window";
    },
    {
      readonly cardinality: "one";
      readonly name: "session";
      readonly targetModel: "session";
    },
  ];
  readonly session: readonly [
    {
      readonly cardinality: "many";
      readonly name: "windows";
      readonly targetModel: "window";
    },
    {
      readonly cardinality: "many";
      readonly name: "panes";
      readonly targetModel: "pane";
    },
    {
      readonly cardinality: "one";
      readonly name: "activeWindow";
      readonly targetModel: "window";
    },
    {
      readonly cardinality: "one";
      readonly name: "activePane";
      readonly targetModel: "pane";
    },
  ];
  readonly window: readonly [
    {
      readonly cardinality: "one";
      readonly name: "session";
      readonly targetModel: "session";
    },
    {
      readonly cardinality: "many";
      readonly name: "linkedSessions";
      readonly targetModel: "session";
    },
    {
      readonly cardinality: "many";
      readonly name: "panes";
      readonly targetModel: "pane";
    },
    {
      readonly cardinality: "one";
      readonly name: "activePane";
      readonly targetModel: "pane";
    },
  ];
}> = Object.freeze({
  client: Object.freeze([
    Object.freeze({ cardinality: "one", name: "session", targetModel: "session" }),
    Object.freeze({ cardinality: "one", name: "window", targetModel: "window" }),
    Object.freeze({ cardinality: "one", name: "pane", targetModel: "pane" }),
  ] as const),
  pane: Object.freeze([
    Object.freeze({ cardinality: "one", name: "window", targetModel: "window" }),
    Object.freeze({ cardinality: "one", name: "session", targetModel: "session" }),
  ] as const),
  session: Object.freeze([
    Object.freeze({ cardinality: "many", name: "windows", targetModel: "window" }),
    Object.freeze({ cardinality: "many", name: "panes", targetModel: "pane" }),
    Object.freeze({ cardinality: "one", name: "activeWindow", targetModel: "window" }),
    Object.freeze({ cardinality: "one", name: "activePane", targetModel: "pane" }),
  ] as const),
  window: Object.freeze([
    Object.freeze({ cardinality: "one", name: "session", targetModel: "session" }),
    Object.freeze({ cardinality: "many", name: "linkedSessions", targetModel: "session" }),
    Object.freeze({ cardinality: "many", name: "panes", targetModel: "pane" }),
    Object.freeze({ cardinality: "one", name: "activePane", targetModel: "pane" }),
  ] as const),
} as const);
